spring:
  application:
    name: music-gateway

server:
  port: 80

zuul:
  routes:
    music:
      url: http://musicbrainz.org/ws/2

ribbon:
  eureka:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, routes, filters